"""
RAGAS Extension for Hybrid Retrieval

This module extends the RAGAS evaluation framework to support hybrid retrieval
evaluation with specialized metrics for hybrid retrieval scenarios.
"""

from typing import Dict, List
import numpy as np
from .hybrid_precision import HybridPrecisionEvaluator
from .information_theory import InformationTheoryMetrics
from .adaptive_weights import AdaptiveWeightOptimizer


class RAGASHybridExtension:
    """
    Extension to RAGAS framework for hybrid retrieval evaluation.

    This class provides specialized evaluation capabilities for hybrid retrieval
    systems, extending the standard RAGAS metrics with hybrid-specific assessments.
    """

    def __init__(self, alpha: float = 0.1, beta: float = 0.1, gamma: float = 0.1):
        """
        Initialize the RAGAS hybrid extension.

        Args:
            alpha: Weight for complexity adjustment in adaptive optimization
            beta: Weight for score difference adjustment
            gamma: Weight for domain confidence adjustment
        """
        self.hybrid_evaluator = HybridPrecisionEvaluator(alpha, beta, gamma)
        self.info_theory = InformationTheoryMetrics()
        self.weight_optimizer = AdaptiveWeightOptimizer(alpha, beta, gamma)

    def evaluate_hybrid_retrieval(
        self,
        query: str,
        retrieved_contexts: List[str],
        generated_answer: str,
        reference_answer: str,
        dense_scores: List[float],
        sparse_scores: List[float],
        **kwargs,
    ) -> Dict[str, float]:
        """
        Evaluate hybrid retrieval performance with extended RAGAS metrics.

        Args:
            query: Input query
            retrieved_contexts: Retrieved contexts from hybrid retrieval
            generated_answer: Answer generated by the RAG system
            reference_answer: Reference/ground truth answer
            dense_scores: Scores from dense retriever
            sparse_scores: Scores from sparse retriever
            **kwargs: Additional parameters

        Returns:
            Dictionary containing extended RAGAS metrics
        """
        # Standard RAGAS metrics (placeholder - would integrate with actual RAGAS)
        standard_metrics = self._calculate_standard_ragas_metrics(
            query, retrieved_contexts, generated_answer, reference_answer
        )

        # Handle edge case for empty scores
        if not dense_scores or not sparse_scores:
            # Return standard metrics only with default hybrid values
            return {
                **standard_metrics,
                "hybrid_precision": 0.0,
                "hybrid_confidence": 0.0,
                "entropy_confidence": 0.0,
                "mutual_information_confidence": 0.0,
                "statistical_confidence": 0.0,
                "dense_weight": 0.7,  # Default weight
                "sparse_weight": 0.3,
                "uncertainty_penalty": 0.0,
            }

        # Hybrid-specific metrics
        hybrid_metrics = self._calculate_hybrid_metrics(
            dense_scores, sparse_scores, query
        )

        # Combined results
        return {**standard_metrics, **hybrid_metrics}

    def _calculate_standard_ragas_metrics(
        self,
        query: str,
        contexts: List[str],
        generated_answer: str,
        reference_answer: str,
    ) -> Dict[str, float]:
        """
        Calculate standard RAGAS metrics.

        Note: This is a simplified implementation. In practice, you would integrate
        with the actual RAGAS library.
        """
        # Placeholder implementation - in real use, integrate with RAGAS library
        return {
            "context_precision": 0.0,  # Would be calculated by RAGAS
            "context_recall": 0.0,
            "faithfulness": 0.0,
            "answer_relevancy": 0.0,
        }

    def _calculate_hybrid_metrics(
        self, dense_scores: List[float], sparse_scores: List[float], query: str
    ) -> Dict[str, float]:
        """Calculate hybrid-specific metrics."""
        # Convert to numpy arrays
        dense_array = np.array(dense_scores)
        sparse_array = np.array(sparse_scores)

        # Use Hybrid Precision evaluator
        hybrid_result = self.hybrid_evaluator.evaluate(
            dense_array, sparse_array, [query]
        )

        # Add hybrid-specific metrics
        hybrid_metrics = {
            "hybrid_precision": hybrid_result["hybrid_precision"],
            "hybrid_confidence": (
                hybrid_result["entropy_confidence"]
                + hybrid_result["mutual_information_confidence"]
                + hybrid_result["statistical_confidence"]
            )
            / 3,
            "entropy_confidence": hybrid_result["entropy_confidence"],
            "mutual_information_confidence": (
                hybrid_result["mutual_information_confidence"]
            ),
            "statistical_confidence": hybrid_result["statistical_confidence"],
            "dense_weight": hybrid_result["adaptive_weights"]["dense"],
            "sparse_weight": hybrid_result["adaptive_weights"]["sparse"],
            "uncertainty_penalty": hybrid_result["uncertainty_penalty"],
        }

        return hybrid_metrics

    def compare_hybrid_vs_standard(
        self, dense_results: Dict, sparse_results: Dict, hybrid_results: Dict
    ) -> Dict[str, float]:
        """
        Compare hybrid retrieval results with standard single-method results.

        Args:
            dense_results: Results from dense-only retrieval
            sparse_results: Results from sparse-only retrieval
            hybrid_results: Results from hybrid retrieval

        Returns:
            Comparison metrics
        """
        comparison = {}

        # Calculate improvements
        if (
            "context_precision" in dense_results
            and "hybrid_precision" in hybrid_results
        ):
            improvement_vs_dense = (
                (
                    hybrid_results["hybrid_precision"]
                    - dense_results["context_precision"]
                )
                / dense_results["context_precision"]
            ) * 100
            comparison["improvement_vs_dense"] = improvement_vs_dense

        if (
            "context_precision" in sparse_results
            and "hybrid_precision" in hybrid_results
        ):
            improvement_vs_sparse = (
                (
                    hybrid_results["hybrid_precision"]
                    - sparse_results["context_precision"]
                )
                / sparse_results["context_precision"]
            ) * 100
            comparison["improvement_vs_sparse"] = improvement_vs_sparse

        # Confidence comparison - always include hybrid confidence score
        if "hybrid_confidence" in hybrid_results:
            comparison["hybrid_confidence_score"] = hybrid_results["hybrid_confidence"]
        else:
            # Default confidence if not provided
            comparison["hybrid_confidence_score"] = 0.5

        return comparison

    def generate_hybrid_report(self, results: Dict[str, float]) -> str:
        """Generate a comprehensive hybrid retrieval evaluation report."""
        report = f"""
Hybrid Retrieval Evaluation Report (RAGAS Extension)
====================================================

Hybrid Precision Score: {results.get('hybrid_precision', 0):.4f}
Hybrid Confidence: {results.get('hybrid_confidence', 0):.4f}

Information Theory Metrics:
- Entropy Confidence: {results.get('entropy_confidence', 0):.4f}
- Mutual Information Confidence: {results.get('mutual_information_confidence', 0):.4f}
- Statistical Confidence: {results.get('statistical_confidence', 0):.4f}

Adaptive Weights:
- Dense Weight: {results.get('dense_weight', 0):.4f}
- Sparse Weight: {results.get('sparse_weight', 0):.4f}

Uncertainty Penalty: {results.get('uncertainty_penalty', 0):.4f}
"""
        return report.strip()

    def get_recommendations(self, results: Dict[str, float]) -> List[str]:
        """Get optimization recommendations based on evaluation results."""
        recommendations = []

        # Check confidence levels - use more specific thresholds
        confidence = results.get("hybrid_confidence", 0)
        if confidence < 0.5:
            recommendations.append(
                "Consider adjusting retrieval parameters to improve confidence"
            )
        elif confidence < 0.7:
            recommendations.append(
                "Moderate confidence - consider fine-tuning retrieval settings"
            )

        # Check uncertainty penalty
        uncertainty_penalty = results.get("uncertainty_penalty", 0)
        if uncertainty_penalty > 0.3:
            recommendations.append(
                "High uncertainty detected - consider domain-specific tuning"
            )
        elif uncertainty_penalty > 0.1:
            recommendations.append(
                "Some uncertainty present - monitor performance closely"
            )

        # Check weight balance
        dense_weight = results.get("dense_weight", 0.7)  # Default values
        sparse_weight = results.get("sparse_weight", 0.3)

        weight_diff = abs(dense_weight - sparse_weight)
        if weight_diff > 0.5:
            recommendations.append(
                "Significant weight imbalance detected - consider rebalancing"
            )
        elif weight_diff > 0.3:
            recommendations.append(
                "Moderate weight imbalance - consider adjusting weights"
            )

        # Only return default message if truly no issues
        if (
            not recommendations
            and confidence >= 0.85
            and uncertainty_penalty <= 0.1
            and weight_diff <= 0.2
        ):
            return ["Hybrid retrieval configuration looks good"]

        return (
            recommendations
            if recommendations
            else ["Monitor performance and adjust as needed"]
        )

    def export_results(self, results: Dict[str, float], filename: str) -> None:
        """Export evaluation results to file."""
        import json

        with open(filename, "w", encoding="utf-8") as f:
            json.dump(results, f, indent=2, ensure_ascii=False)

    @staticmethod
    def load_results(filename: str) -> Dict[str, float]:
        """Load evaluation results from file."""
        import json

        with open(filename, "r", encoding="utf-8") as f:
            return json.load(f)
